# Generated by Django 5.2.5 on 2025-08-27 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('products', '0002_product_description_en_product_description_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='discount',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='discount',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='discount',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], verbose_name='Discount type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ordered at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.promocode', verbose_name='Promocode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Purchased at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.BigIntegerField(verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='payments.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.BigIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='products.productvariant', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_discounts', to='payments.discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discounts', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum amount'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage limit'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='promocodeusage',
            name='promocode_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usages', to='payments.promocode', verbose_name='Promocode'),
        ),
        migrations.AlterField(
            model_name='promocodeusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Used at'),
        ),
    ]
